### ISSUE TITLE
Epic: Get complement-crypto running in rust SDK CI

### ISSUE THREAD

**Issue by kegsay** [matrix-org/complement-crypto#25]
- [ ] https://github.com/matrix-org/complement-crypto/issues/6
- [ ] https://github.com/matrix-org/complement-crypto/issues/21
- [ ] https://github.com/matrix-org/complement-crypto/issues/24
- [ ] https://github.com/matrix-org/complement-crypto/issues/22
